service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: femasters
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:  
  api:
    handler: src/api/api.handler
    events: 
      - http: 
          path: /api
          method: get
          cors: true
  todos:
    handler: src/api/todos.handler
    events: 
      - http: 
          path: /todos
          method: get
          cors: true
    
  todo:
    handler: src/api/todo.handler
    events:
      - http: 
          path: /todos/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
    
